apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: clone-hello
spec:
  params:
    # - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: clone-hello-
      spec:
        pipelineRef:
          name: clone-hello
        podTemplate:
          securityContext:
            fsGroup: 65532
        workspaces:
          - name: workdir
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: dockerconfig
            secret:
              secretName: dockerconfig
        params:
          - name: repo-url
            value: $(tt.params.gitrepositoryurl)